spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: postgres
    password: Nadzh1995
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
